apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app_dep: second-app
  template: 
    metadata:
      labels:
        app_dep: second-app
    spec:
      containers: 
        - name: second-nodejs
          image: khairnardev/kub-first-app